### ISSUE TITLE
Notebooks are not working

### ISSUE THREAD

**Issue by Georgii-Mamistvalov** [kevinmicha/ANTIPASTI#3]
Hello!

I am trying to run your notebooks, but keep getting assertion error

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[3], line 13
     10 scfv = ['4gqp', '3etb', '3gkz', '3uze', '3uzq', '3gm0', '4f9l', '6ejg', '6ejm', '1h8s', '5dfw', '6cbp', '4f9p', '5kov', '1dzb', '5j74', '5aaw', '3uzv', '5aam', '3ux9', '5a2j', '5a2k', '5a2i', '3fku', '5yy4', '3uyp', '5jyl', '1y0l', '1p4b', '3kdm', '4lar', '4ffy', '2ybr', '1mfa', '5xj3', '5xj4', '4kv5', '5vyf'] 
     11 pathological += scfv
---> 13 preprocessed_data = Preprocessing(data_path = '[/home/georgii/PycharmProjects/CSM-AB2/ANTIPASTI/data/](http://localhost:8889/lab/tree/data/)', dccm_map_path=dccm_map_path, modes=modes, pathological=pathological, renew_maps=renew_maps, renew_residues=renew_residues, ag_agnostic=ag_agnostic, cmaps=contact_maps, cmaps_thr=cmaps_thr)

File [~/PycharmProjects/CSM-AB2/ANTIPASTI/antipasti/preprocessing/preprocessing.py:131](http://localhost:8889/lab/tree/antipasti/preprocessing/preprocessing.py#line=130), in Preprocessing.__init__(self, data_path, scripts_path, structures_path, df, modes, chain_lengths_path, dccm_map_path, residues_path, file_type_input, selection, pathological, renew_maps, renew_residues, cmaps, cmaps_thr, ag_agnostic, affinity_entries_only, stage, test_data_path, test_dccm_map_path, test_residues_path, test_structure_path, test_pdb_id, alphafold, h_offset, l_offset, ag_residues)
    129 self.df_path = data_path + df
    130 self.entries, self.affinity, self.df = self.clean_df()
--> 131 self.heavy, self.light, self.selected_entries = self.initialisation(renew_maps, renew_residues)
    132 self.max_res_list_h, self.max_res_list_l, self.min_res_list_h, self.min_res_list_l = self.get_max_min_chains()
    133 self.train_x, self.train_y, self.labels, self.raw_imgs = self.load_training_images()

File [~/PycharmProjects/CSM-AB2/ANTIPASTI/antipasti/preprocessing/preprocessing.py:453](http://localhost:8889/lab/tree/antipasti/preprocessing/preprocessing.py#line=452), in Preprocessing.initialisation(self, renew_maps, renew_residues)
    450     heavy = np.load(self.chain_lengths_path+'heavy_lengths.npy').astype(int)
    451     light = np.load(self.chain_lengths_path+'light_lengths.npy').astype(int)
--> 453 assert list(np.load(self.chain_lengths_path+'selected_entries.npy')) == selected_entries
    455 for entry in selected_entries:
    456     assert len(np.load(self.residues_path+entry+'.npy'))-2 == heavy[selected_entries.index(entry)] + light[selected_entries.index(entry)]

AssertionError:

P.S. 
Also I had issues with data_path -- user needs to give it manually

**Comment by kevinmicha** [comment]
Hi Georgii, thank you for opening this issue. We are currently under the review process, so modifications are being made. Everything will be updated and in working conditions very soon.
