### ISSUE TITLE
How to Align AlphaFold2 Predicted Structures to Chothia Numbering for Antipasti Model Prediction?

### ISSUE THREAD

**Issue by dezhi0730** [kevinmicha/ANTIPASTI#4]
Hello,

I hope this message finds you well. I have been working with AlphaFold2 to predict the structures of antibody complexes and I am interested in aligning these structures to the Chothia numbering scheme before using them for predictions with the Antipasti model.

Could you please provide guidance or recommend any tools/methods for:

- Converting AlphaFold2 predicted PDB structures to Chothia numbering.

Any detailed steps or references to relevant resources would be greatly appreciated. Thank you for your assistance!

Best regards!

**Comment by kevinmicha** [comment]
Hi,

Thank you for your message. Typically, you should not need to perform the conversion yourself for AF models, provided you have a corresponding PDB file with Chothia numbering.

However, if this is not the case, you might find [this](https://github.com/Graylab/IgFold/blob/85d9dcdbc7afb9c38c4427df656fc194a61bd6ee/igfold/utils/abnumber_.py#L37) function helpful. Although I have not tested it myself, it appears straightforward and promising. It is part of the [IgFold](https://github.com/Graylab/IgFold/) repository and [AbNumber](https://github.com/prihoda/AbNumber)-based.

Hope this helps!

**Comment by dezhi0730** [comment]
Hi Kevin,

Thank you for your message. I have successfully obtained the corresponding PDB file with Chothia numbering.

However, I encountered difficulties when running [load_test_image](https://github.com/kevinmicha/ANTIPASTI/blob/main/antipasti/preprocessing/preprocessing.py#L589) on a new PDB file because there is no corresponding `list_of_residues`.

Could you provide some suggestions or methods for：

- Obtain the corresponding `list_of_residues` for a newly predicted PDB file with Chothia numbering

Best regards!

**Comment by kevinmicha** [comment]
Solved issue.

**Comment by bioermaf** [comment]
> Hello,
> 
> I hope this message finds you well. I have been working with AlphaFold2 to predict the structures of antibody complexes and I am interested in aligning these structures to the Chothia numbering scheme before using them for predictions with the Antipasti model.
> 
> Could you please provide guidance or recommend any tools/methods for:
> 
> * Converting AlphaFold2 predicted PDB structures to Chothia numbering.
> 
> Any detailed steps or references to relevant resources would be greatly appreciated. Thank you for your assistance!
> 
> Best regards!

I encountered the same problem. May I ask for details of the solution? Thank you very much.

**Comment by bioermaf** [comment]
> Hi Kevin,
> 
> Thank you for your message. I have successfully obtained the corresponding PDB file with Chothia numbering.
> 
> However, I encountered difficulties when running [load_test_image](https://github.com/kevinmicha/ANTIPASTI/blob/main/antipasti/preprocessing/preprocessing.py#L589) on a new PDB file because there is no corresponding `list_of_residues`.
> 
> Could you provide some suggestions or methods for：
> 
> * Obtain the corresponding `list_of_residues` for a newly predicted PDB file with Chothia numbering
> 
> Best regards!

I encountered the same problem. May I ask for details of the solution? Thank you very much.
