### ISSUE TITLE
How can I input an antibody PDB and a antigen PDB for the affinity prediction?

### ISSUE THREAD

**Issue by tonyreina** [kevinmicha/ANTIPASTI#6]
This looks like an excellent project. Thanks for providing it!

I am able to run through the notebooks, but I'm having trouble wrapping my head around how to preprocess the antigen/antibody inputs. I assume everything I need is in this line:

`preprocessed_data = Preprocessing(dccm_map_path=dccm_map_path, modes=modes, pathological=pathological, stage=stage, test_data_path=test_data_path, test_dccm_map_path=test_dccm_map_path, test_residues_path=test_residues_path, test_structure_path=test_structure_path, test_pdb_id=test_pdb, renew_residues=True, alphafold=False)`

Can you help me understand the parameters here?

Is there a simple way for me to just give it the PDB for the antigen and the PDB for the antibody to get an affinity prediction?

Thanks.
-Tony

**Comment by kevinmicha** [comment]
Hi Tony,

Glad to hear you liked the project! We've put together a full documentation of ANTIPASTI, meaning you can dive into the details of all the functions and classes in the package. For `Preprocessing`, you can go [here](https://kevinmicha.github.io/ANTIPASTI/apidoc/antipasti.preprocessing.html#antipasti.preprocessing.preprocessing.Preprocessing). 

There's a simple way to provide a PDB file and get an affinity prediction. First of all, make sure it follows the Chothia numbering scheme for the antibody chains. Then, place the file under `notebooks/test_data/structure/`. Finally, run the notebok [[Tutorial] Predicting affinity using ANTIPASTI.ipynb](https://github.com/kevinmicha/ANTIPASTI/blob/main/notebooks/%5BTutorial%5D%20Predicting%20affinity%20using%20ANTIPASTI.ipynb) by adapting the `test_pdb` variable.

Hope this helps!

Best,
Kevin

**Comment by tonyreina** [comment]
Excellent. I'll take a look. Thanks so much again.

Best.
-Tony

**Comment by kevinmicha** [comment]
Hi Tony,

ANTIPASTI is meant to be used on antibody-antigen complexes that are correctly docked. We did some docking tests and learnt that if the docking is incorrect, then the affinity values deviate from the expected ones, even obtaining out-of-range results (which is expected). However, in all the cases the antibody and antigen are docked together.

Sorry if this isn't quite what you were hoping for!

**Comment by tonyreina** [comment]
No worries. I was just hoping! 

I thought I could apply it to the TDC Commons sAbDab dataset:  https://tdcommons.ai/multi_pred_tasks/antibodyaff
